abdiGroup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('capabilities.urls', namespace='home')),
    path('capabilities/', include('capabilities.urls', namespace='capabilities')),
    path('product-and-services/', include('product_and_services.urls', namespace ='product-and-services')),
    path('company', include('company.urls', namespace='company')),
    path('mr-dr', include('mr_dr.urls', namespace='mr-dr')),
    path('oil-and-gas-news/', include('news.urls', namespace='news')),
    # ckeditor 
    path('ckeditor/', include('ckeditor_uploader.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

capabilities/urls.py
from os import name
from django.urls import path
from .views import capabilities

app_name = 'capabilities'

urlpatterns = [
    path('', capabilities, name='capabilities' )
]

mr_dr/urls.py
from django.urls import path
from .views import mr_dr

app_name= 'mr-dr'

urlpatterns = [
    path('', mr_dr, name='mr-dr'),
]

news/urls.py
from django.urls import path
from .views import NewsPage, NewsDetail

app_name = 'news'

urlpatterns = [
    path('', NewsPage.as_view(), name='news-page'),
    path('<int:id>/', NewsDetail.as_view(), name='news-detail')
]

templates/base.html
{% load i18n %} {% load static %} {% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta-descriptions %}{% endblock meta-descriptions %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% if LANGUAGE_CODE == 'fa' %}
      <link rel="stylesheet" href="{% static 'css/base-fa.css' %}">
    {% endif %}
    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <!-- fonts END -->
    <!-- more css -->
    {% block more_css %} {% endblock %}
    <!-- more css END -->
    <title>{% trans "Abdi Group"%} | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <!-- header & navbar  -->
    <header>
      <ul class="header-btns .md-none">
        <li><a href="{% url 'mr-dr:mr-dr' %}"><img src="{% static 'svgs/help-circle.svg' %}" alt="globe icon"><h4>{% trans "Mr.Dr" %}</h4></a></li>
        <li><a href="{% url 'news:news-page' %}"><img src="{% static 'svgs/bell.svg' %}" alt="globe icon"><h4>{% trans "News" %}</h4></a></li>
        <li>
          {% if LANGUAGE_CODE == 'fa' %}
            {% language 'en' %}
              <a id='language-changer' href="{% block translateFa %}{% endblock translateFa %}"><h4>FA</h4><img src="{% static 'svgs/globe.svg' %}" alt="globe icon"></a>
            {% endlanguage %}
          {% else %}
            {% language 'fa' %}
              <a id='language-changer' href="{% block translateEn %}{% endblock translateEn %}"><img src="{% static 'svgs/globe.svg' %}" alt="globe icon"><h4>EN</h4></a>
            {% endlanguage %}
          {% endif %}
        </li>
      </ul>
      {% comment %} {% if LANGUAGE_CODE == 'fa' %}
        {% language 'en' %}
          <a class='lan-changer' href="{% block translateFa %}{% endblock translateFa %}"><h3>FA</h3><img src="{% static 'svgs/globe.svg' %}" alt="globe icon"></a>
        {% endlanguage %}
      {% else %}
        {% language 'fa' %}
          <a class='lan-changer' href="{% block translateEn %}{% endblock translateEn %}"><img src="{% static 'svgs/globe.svg' %}" alt="globe icon"><h3>EN</h3></a>
        {% endlanguage %}
      {% endif %} {% endcomment %}
      {% include 'inc/mobile-navbar.html' %}
      <nav>
        {% if LANGUAGE_CODE == 'fa' %}
        <h3 class='company-fa-name'>گروه خدمات مهندسی نفت گاز پتروشیمی عبدی</h3>
        <h5 class='company-fa-name'>(سهامی خاص)</h5>
          <img id='company-name' src="{% static 'svgs/fa-name.svg' %}" alt="company">
          <a href="{% url 'capabilities:capabilities' %}">
            <img
              id="logo"
              src=" {% static 'images/logo-fa.webp' %} "
              alt="abdi-group"
            />
          </a>
        {% else %}
          <img id='company-name' src="{% static 'svgs/l-name.svg' %}" alt="">
          <a href="{% url 'capabilities:capabilities' %}">
            <img
              id="logo"
              src=" {% static 'images/logo.png' %} "
              alt="abdi-group"
            />
          </a>
        {% endif %}
        <!--language changer & mobile menu button-->
        <div class="img__btns">
          {% if LANGUAGE_CODE == 'fa' %}
            {% language 'en' %}
              <a class='lan-changer-mobile' href="{% block translateFaMobile %}{% endblock translateFaMobile %}"><img src="{% static 'svgs/mobile-globe.svg' %}" alt="globe icon"></a>
            {% endlanguage %}
            <img
              id="logo"
              src=" {% static 'images/logo-fa.webp' %} "
              alt="abdi-group"
            />
          {% else %}
            {% language 'fa' %}
              <a class='lan-changer-mobile' href="{% block translateEnMobile %}{% endblock translateEnMobile %}"><img src="{% static 'svgs/mobile-globe.svg' %}" alt="globe icon"></a>
            {% endlanguage %}
            <img
              id="logo"
              src=" {% static 'images/logo.png' %} "
              alt="abdi-group"
              style='top: 1rem;'
            />
          {% endif %}
          <img
            id="mobile-menu-btn"
            src=" {% static 'svgs/menu.svg' %} "
            alt=""
          />
        </div>
        {% include 'inc/navbar.html' %}
      </nav>
    </header>
    {% block content %}
    {% endblock %}
    {% include 'inc/footer.html' %}
    <!-- js files -->
      <!-- GSAP animation -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/ScrollTrigger.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/ScrollToPlugin.min.js"></script>
      <script src=" {% static 'js/base.js' %} "></script>
    <!-- more js -->
      {% block more_js %}{% endblock more_js %}
  </body>
</html>