abdiGroup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('capabilities.urls', namespace='home')),
    path('capabilities/', include('capabilities.urls', namespace='capabilities')),
    path('product-and-services/', include('product_and_services.urls', namespace ='product-and-services')),
    path('company', include('company.urls', namespace='company')),
    path('mr-dr', include('mr_dr.urls', namespace='mr-dr')),
    path('oil-and-gas-news/', include('news.urls', namespace='news')),
    # ckeditor 
    path('ckeditor/', include('ckeditor_uploader.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

capabilities/urls.py
from os import name
from django.urls import path
from .views import capabilities

app_name = 'capabilities'

urlpatterns = [
    path('', capabilities, name='capabilities' )
]

company/urls.py
from os import name
from django.urls import path
from .views import company

app_name = 'company'

urlpatterns = [
    path('', company, name='company' )
]

news/urls.py
from django.urls import path
from .views import NewsPage, NewsDetail

app_name = 'news'

urlpatterns = [
    path('', NewsPage.as_view(), name='news-page'),
    path('<int:id>/', NewsDetail.as_view(), name='news-detail')
]

product_and_services/urls.py
from django.urls import path
from .views import civil_projects, ffs_ftp, inline_inspections, cathodic_protection, under_water_inspection, cleaning_pigs, unpigable_pipelines, repairing, ffs_ftp, leak_detection, valve_clinic, inspection, process_units, industrial_technology, management_systems

app_name = 'product-and-services'

urlpatterns = [
    path('oil-and-gas-pipelines/inline-inspection/', inline_inspections, name='inline-inspection'),
    path('oil-and-gas-pipelines/cathodic-protection/', cathodic_protection, name='cathodic-protection'),
    path('oil-and-gas-pipelines/under-water-inspection/', under_water_inspection, name='under-water-inspection'),
    path('oil-and-gas-pipelines/cleaning-pigs/', cleaning_pigs, name='cleaning-pigs'),
    path('oil-and-gas-pipelines/unpigable-pipelines/', unpigable_pipelines, name='unpigable-pipelines'),
    path('oil-and-gas-pipelines/repairing/', repairing, name='repairing'),
    path('oil-and-gas-pipelines/ffs-ftp/', ffs_ftp, name='ffs-ftp'),
    path('oil-and-gas-pipelines/leak-detection/', leak_detection, name='leak-detection'),
    path('oil-and-gas-pipelines/valve-clinic/', valve_clinic, name='valve-clinic'),
    path('oil-and-gas-pipelines/inspection/', inspection, name='inspection'),

    path('civil-projects/', civil_projects, name='civil-projects'),
    path('process-units/', process_units, name='process-units'),
    path('industrial-technology/', industrial_technology, name='industrial-technology'),
    path('management-systems/', management_systems, name='management-systems'),
]

templates/inc/footer.html
{% load static %} {% load i18n %} {% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block more_css %}
        <link rel="stylesheet" href="{% static 'css/footer.css' %}" />
      {% if LANGUAGE_CODE == 'fa' %}
        <link rel="stylesheet" href="{% static 'css/footer-fa.css' %}">
      {% endif %}
    {% endblock more_css %}
    <title>Document</title>
</head>
<body>
    <footer>
      {% if LANGUAGE_CODE == 'fa' %}
        <img src="{% static 'svgs/footer-hexa-fa.svg' %}" alt='alt="footer hexagons svg"'>
      {% else %}
        <img src="{% static 'svgs/footer-hexa.svg' %}" alt="footer hexagons svg">
      {% endif %}
      <div class="container">
        <img class='footer-top-icon' src="{% static 'svgs/footer-top-icon.svg' %}" alt="footer top svg">
        <img onclick='goUpFunction()' id='go-up-btn' src="{% static 'svgs/go-up-btn.svg' %}" alt="go up button">
        <div class="lists-wrapper">
          <ul class="footer-list">
            <div class="title">
              <img src=" /static/capabilities/svgs/3hexaIcon.svg " alt="3hexaIcon">
              <h3>{% trans "Useful Links" %}</h3>
            </div>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'capabilities:capabilities' %}">{% trans "Capabilities" %}</a>
            </li>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:process-units' %}">{% trans "Process Units" %}</a>
            </li>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:civil-projects' %}">{% trans "Civil Projects" %}</a>
            </li>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:industrial-technology' %}">{% trans "Industrial Technology" %}</a>
            </li>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:management-systems' %}">{% trans "Management Systems" %}</a>
            </li>
          </ul>
          <ul class="footer-list">
            <div class="title">
              <img src=" /static/capabilities/svgs/3hexaIcon.svg " alt="3hexaIcon">
              <h3>{% trans "Products and Services" %}</h3>
            </div>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:inline-inspection' %}">{% trans "Inline Inspection" %}</a>
            </li>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:unpigable-pipelines' %}">{% trans "Unpigable Pipelines" %}</a>
            </li>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:under-water-inspection' %}">{% trans "Under Water Inspection-ROV" %}</a>
            </li>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:cleaning-pigs' %}">{% trans "Cleaning Pigs" %}</a>
            </li>
            <li>
              <img src=" /static/svgs/s-green-hexa.svg " alt="3hexaIcon">
              <a href="{% url 'product-and-services:cathodic-protection' %}">{% trans "Coating and Cathodic Protection" %}</a>
            </li>
          </ul>
          <ul class="footer-list">
            <div class="title">
              <img src=" /static/capabilities/svgs/3hexaIcon.svg " alt="3hexaIcon">
              <h3>{% trans "Contact Us" %}</h3>
            </div>
            <li>
              <img src="{% static 'svgs/phone.svg' %}" alt="phone icon">
              <a href="tel:02122006761">{% trans "+98-021-22006761" %}</a>
            </li>
            <li>
              <img src="{% static 'svgs/printer.svg' %}" alt="fax icon">
              <a href="tel:02122638734">{% trans "+98-021-22638734" %}</a>
            </li>
            <li>
              <img src="{% static 'svgs/mail.svg' %}" alt="fax icon">
              <a href="mailto:info@abdi-group.com">info@abdi-group.com</a>
            </li>
            <li id='address'>
              <img src="{% static 'svgs/map-pin.svg' %}" alt="map pin icon">
              <p>{% trans "Un.5 No-1 Rokni Dead End, Khorosh St, Varaste St, Dolat <br> St, Pasdaran, Tehran" %}</p>
            </li>
          </ul>
        </div>
      </div>
      <div class="policy-wrapper">
        <div class="container">
          <div class="social-media-btns-wrapper">
            <a href=""><img src="{% static 'svgs/facebook.svg' %}" alt="Facebook"></a>
            <a href="https://ir.linkedin.com/in/hossein-abdi-5889463a"><img src="{% static 'svgs/linkedin.svg' %}" alt="Linkedin"></a>
            <a href="/"><img src="{% static 'svgs/telegram.svg' %}" alt="Telegram"></a>
            <a href="/"><img src="{% static 'svgs/whatsapp.svg' %}" alt="Whatsapp"></a>
          </div>
          <div id="navid">
            <a href="mailto:navidazimi1380@gmail.com">
              <img src="{% static 'svgs/navid-logo.svg' %}" alt="navid's logo">
              <p>{% trans "Programmed and designed by" %} <span>{% trans "Navid Azimi" %}</span></p>
            </a>
          </div>
        </div>
        {% comment %} <h3 class='copyright'>{% trans "Copyright © 2021 abdi group. All Rights Reserved" %}</h3> {% endcomment %}
      </div>
    </footer>
    {% block more_js %}
      <script src="{% static 'js/footer.js' %}"></script>
    {% endblock more_js %}
</body>
</html>

templates/inc/hero.html
{% load static %} {% block more_css %}
<link rel="stylesheet" href="{% static 'css/hero.css' %}" />
{% endblock more_css %}

<section class="hero">
  <div class="main-img-wrapper">
    <div class="img">
      <div class="fade-layer"></div>
      <img class="main-img" src="{% static img %}" alt="hero-img" />
    </div>
  </div>
  <img
    class="desktop-hero-hexa"
    src="{% static page_image %}"
    alt="green hexagons"
  />
  <img
    class="main-img-hexagons-right"
    src="{% static 'svgs/mobile-hero-hexas-right.svg' %}"
    alt="mobile green hexagons"
  />
  <img
    class="main-img-hexagons-left"
    src="{% static 'svgs/mobile-hero-hexas-left.svg' %}"
    alt="mobile green hexagons"
  />
</section>

templates/inc/mobile-navbar.html
{% load static %} {% load i18n %} {% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/mobile-navbar.css' %}" />
    {% if LANGUAGE_CODE == 'fa' %}
      <link rel="stylesheet" href="{% static 'css/mobile-navbar-fa.css' %}">
    {% endif %}
</head>
<body>
     <div id="mobile-menu">
        <div id="menu__btns">
          <img
            onclick="goBackBtnF()"
            id="go-back-btn"
            src="{% static 'svgs/go-back-btn.svg' %}"
            alt="go back button"
          />
          <img
            id="close-menu-btn"
            src="{% static 'svgs/menu-X.svg' %}"
            alt="close navbar button"
          />
        </div>
        <ul id="menu-list">
          <li>
            <a href="{% url 'capabilities:capabilities' %}">
              <p>{% trans "Capabilities" %}</p>
              <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
            </a>
          </li>
          <li id="products">
              <p>{% trans "Products and Services" %}</p>
              <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
          </li>
          <li>
            <a href="{% url 'company:company' %}">
              <p>{% trans "About Us" %}</p>
              <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon"
            /></a>
          </li>
          <li>
            <a href="{% url 'news:news-page' %}">
              <p>{% trans "Oil And Gas News" %}</p>
              <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
            </a>
          </li>
        </ul>
        <ul id="menu-sub-list">
          <li onclick="openSubMenuSub(0)">
            <p>{% trans "Oil and Gas Pipelines" %}</p>
            <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
          </li>
          <li onclick="openSubMenuSub(1)">
            <a href='{% url 'product-and-services:civil-projects' %}'>{% trans "Civil Projects" %}</a>
            <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
          </li>
          <li onclick="openSubMenuSub(2)">
            <a href='{% url 'product-and-services:process-units' %}'>{% trans "Process Units" %}</a>
            <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
          </li>
          <li onclick="openSubMenuSub(3)">
            <a href='{% url 'product-and-services:industrial-technology' %}'>{% trans "Industrial Technology" %}</a>
            <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
          </li>
          <li onclick="openSubMenuSub(4)">
            <a href='{% url 'product-and-services:management-systems' %}'>{% trans "Management Systems" %}</a>
            <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
          </li>
        </ul>
        <ul id="menu-sub-list-sub">
          <ul>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />

              <a href="{% url 'product-and-services:inline-inspection' %}">{% trans "Inline Inspection" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href="{% url 'product-and-services:unpigable-pipelines' %}">{% trans "Unpigable Pipelines" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href="{% url 'product-and-services:under-water-inspection' %}">{% trans "Under Water Inspection-ROV" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href="{% url 'product-and-services:cleaning-pigs' %}">{% trans "Cleaning Pigs" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href="{% url 'product-and-services:repairing' %}">{% trans "Repairing" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href="{% url 'product-and-services:valve-clinic' %}">{% trans "Valve Clinic" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href="{% url 'product-and-services:cathodic-protection' %}">{% trans "Coating and Cathodic Protection" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href="{% url 'product-and-services:cathodic-protection' %}>{% trans "Inspection(Fixed Equipment and Instruments)" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href="{% url 'product-and-services:ffs-ftp' %}">{% trans "Fitness For Services(FFS) and Fitness For Purpose(FFP)" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px !important"
              />
              <a href="{% url 'product-and-services:leak-detection' %}">{% trans "Leak Detection" %}</a>
            </li>
            <li>
              <img
                src="{% static 'svgs/small-list-dot.svg' %}"
                alt="small-list-dot"
                width="8px"
              />
              <a href='{% url 'product-and-services:leak-detection' %}'>{% trans "Consultant and Project Management" %}</a>
            </li>
          </ul>
          <ul>
            <li>2</li>
            <li>2</li>
            <li>2</li>
          </ul>
        </ul>
        <div onclick="changeSubMenu()" id="sub-menu-btn">
          <img src="{% static 'svgs/menu-opt-arrow.svg' %}" alt="arrow icon" />
        </div>
      </div>
  {% block more_js %}
      {% comment %} <script src="{% static 'js/mobile-navbar.js' %}"></script> {% endcomment %}
    {% if LANGUAGE_CODE == 'fa' %}
      <script src="{% static 'js/mobile-navbar-fa.js' %}"></script>
    {% endif %}
  {% endblock more_js %}
</body>
</html>

templates/inc/navbar.html
{% load static %} {% load i18n %} {% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block more_css %}
        <link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
      {% if LANGUAGE_CODE == 'fa' %}
        <link rel="stylesheet" href="{% static 'css/navbar-fa.css' %}">
      {% endif %}
    {% endblock more_css %}
    <title>Document</title>
  </head>
  <body>
    <div id="navbar">
      <div class="navbar-btns">
        <img
          onclick="ChangeLan()"
          id="nav-list-lang-btn"
          src="{% static 'svgs/navbar-globe.svg' %}"
          alt="language changer"
        />
        <img
          onclick="NavListClickHandler()"
          id="nav-list-cross-btn"
          src="{% static 'svgs/menu-X.svg' %}"
          alt="cross"
        />
      </div>
      <ul>
        <li>
          <img src="{% static 'svgs/navbar-hexa.svg' %}" alt="navbar hexagon icon" />
          <a href=" {% url 'capabilities:capabilities' %} ">{% trans "Capabilities" %}</a>
        </li>
        <li id='product-and-services'>
          <img src="{% static 'svgs/navbar-hexa.svg' %}" alt="navbar hexagon icon" />
          <p onclick="NavListClickHandler()">{% trans "Products and Services" %}</p>
        </li>
        <li>
          <img src="{% static 'svgs/navbar-hexa.svg' %}" alt="navbar hexagon icon" />
          <a href="{% url 'company:company' %}">{% trans "About Us" %}</a>
        </li>
      </ul>
      <div id="navlist">

        {% if LANGUAGE_CODE == 'fa' %}
           <img
          id="desktop-nav-list-hexa"
          class='desktop-nav-list-hexa-fa'
          src="{% static 'svgs/desktop-navlist-hexa-fa.svg' %}"
          alt=""
        />
        {% endif %}
        {% if LANGUAGE_CODE == 'en' %}
        <img
          id="desktop-nav-list-hexa"
          src="{% static 'svgs/desktop-navlist-hexa.svg' %}"
          alt=""
        />
        {% endif %}
        <ul id="desktop-nav-list-ul">
          <li class="desktop-nav-list-li">
            <h2 onclick="openDesktopNavList(0)">{% trans "Oil and Gas Pipelines" %}</h2>
          </li>
          <li class="desktop-nav-list-li">
            <a href="{% url 'product-and-services:process-units' %}"><h2>{% trans "Process Units" %}</h2></a>
          </li>
          <li class="desktop-nav-list-li">
            <a href="{% url 'product-and-services:civil-projects' %}"><h2>{% trans "Civil Projects" %}</h2></a>
          </li>
          <li class="desktop-nav-list-li">
            <a href="{% url 'product-and-services:industrial-technology' %}"><h2>{% trans "Industrial Technology" %}</h2></a>
          </li>
          <li class="desktop-nav-list-li">
            <a href="{% url 'product-and-services:management-systems' %}"><h2>{% trans "Management Systems" %}</h2></a>
          </li>
          <li class="desktop-nav-list-li">
            <a href="{% url 'news:news-page' %}"><h2>{% trans "Oil And Gas News" %}</h2></a>
          </li>
        </ul>
        <div class="desktop-nav-list-options-wrapper">
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:inline-inspection' %}">{% trans "Inline Inspection" %}</a></div>
          <div class="desktop-nav-list-options coming-soon"><a href="#" onclick="return false;">{% trans "Unpigable Pipelines" %} <br>{% trans "(Coming Soon)" %}</a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:under-water-inspection' %}">{% trans "Under Water Inspection-ROV" %}</a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:cleaning-pigs' %}">{% trans "Cleaning Pigs" %}{% if LANGUAGE_CODE == 'fa' %}<span>( تامین ژل پیگها و پیگهای ویژه بر حسب نیازمندیها )</span>{% endif %}</a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:repairing' %}">{% trans "Repairing" %}</a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:valve-clinic' %}">{% trans "Valve Clinic" %}</a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:cathodic-protection' %}">{% trans "Coating and Cathodic Protection" %}</a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:inspection' %}">{% trans "Inspection" %}<span style='font-size:12px;'>{% trans "(Fixed Equipment and Instruments)" %}</span></a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:ffs-ftp' %}">{% trans "Fitness For Services(FFS) and Fitness For Purpose(FFP)" %}</a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:leak-detection' %}">{% trans "Leak Detection" %}<span>{% trans "(FID, Laser, Mobile/Vehicle , Satellite Images)" %}</span></a></div>
          <div class="desktop-nav-list-options"><a href="{% url 'product-and-services:cathodic-protection' %}">{% trans "Consultant and Project Management" %}</a></div>
        </div>
        <div class="desktop-nav-list-options-wrapper">
          <div class="desktop-nav-list-options">{% trans "Remediation of Polluted Soil by oil or industrial waste" %}</div>
          <div class="desktop-nav-list-options">{% trans "Pipeline Chemical Cleaning" %}</div>
          <div class="desktop-nav-list-options">{% trans "Special Tools" %}</div>
          <div class="desktop-nav-list-options">{% trans "Leak Detection by Satellite Images" %}</div>
          <div class="desktop-nav-list-options">{% trans "Technology Transfer" %}</div>
        </div>
        <div class="desktop-nav-list-options-wrapper">
          <div class="desktop-nav-list-options">{% trans "Pipeline Integrity Management System" %}</div>
          <div class="desktop-nav-list-options">{% trans "Asset Integrity Management" %}</div>
          <div class="desktop-nav-list-options">{% trans "Risk Management" %}</div>
        </div>
      </div>
    </div>
    {% block more_js %}
      <script src="{% static 'js/navbar.js' %}"></script>
    {% endblock more_js %}
  </body>
</html>