abdiGroup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('capabilities.urls', namespace='home')),
    path('capabilities/', include('capabilities.urls', namespace='capabilities')),
    path('product-and-services/', include('product_and_services.urls', namespace ='product-and-services')),
    path('company', include('company.urls', namespace='company')),
    path('mr-dr', include('mr_dr.urls', namespace='mr-dr')),
    path('oil-and-gas-news/', include('news.urls', namespace='news')),
    # ckeditor 
    path('ckeditor/', include('ckeditor_uploader.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import NewsPage, NewsDetail

app_name = 'news'

urlpatterns = [
    path('', NewsPage.as_view(), name='news-page'),
    path('<int:id>/', NewsDetail.as_view(), name='news-detail')
]

news/models.py
from email.policy import default
from django.db import models
from ckeditor.fields import RichTextField
from jalali_date import datetime2jalali, date2jalali

class News(models.Model):
  title = models.CharField(max_length=250, blank=True, null=True)
  summery = RichTextField(blank=True, null=True)
  image = models.ImageField(upload_to='news-images/%Y/%m/%d/', blank=True, null=True)
  body = RichTextField(blank=True, null=True)
  created = models.DateTimeField(auto_now=True, blank=True, null=True)

  def __str__(self):
    return self.title

  def jalali_date(self):
    return date2jalali(self.created)

news/views.py
from django.shortcuts import render
from django.views import View
from .models import News

class NewsPage(View):
  def get(self, request):
    news = News.objects.all()
    return render(request, 'news-page.html', {'news':news})

class NewsDetail(View):
  def get(self, request, id):
    news = News.objects.get(id=id)
    return render(request, 'news.html', {'news':news})

news/templates/news-page.html
{% extends 'base.html' %} {% load i18n %} {% load static %} {% load jalali_tags %}
{% block translateFa %}{% url 'news:news-page' %}{% endblock translateFa %} 
{% block translateEn %}{% url 'news:news-page' %}{% endblock translateEn %} 
{% block translateEnMobile %}{% url 'news:news-page' %}{% endblock translateEnMobile %} 
{% block translateFaMobile %}{% url 'news:news-page' %}{% endblock translateFaMobile %}
{% block more_css %}
  <link rel="stylesheet" href="{% static 'news/css/news-page.css' %}">
  {% if LANGUAGE_CODE == 'fa' %}
    <link rel="stylesheet" href="{% static 'news/css/news-page-fa.css' %}">
  {% endif %}
{% endblock more_css %}
{% comment %} {% block meta-descriptions %}
<meta
  name="description"
  content="ABDI-GROUP, relying on more than half a century of experience in construction projects, Provides design and construction services for civil projects as well as construction project management."
/>
{% endblock meta-descriptions %} {% endcomment %}
{% block title %}{% trans "Oil And Gas News" %}{% endblock title %}
{% block content %}
{% if LANGUAGE_CODE == 'fa' %}
  {% include 'inc/hero.html' with img='capabilities/images/gas-pipeline-ai.webp' page_image='svgs/civil-projects-hexa.svg' page_image='svgs/oil-and-gas-news-hexa-fa.svg' %}
{% else %}
  {% include 'inc/hero.html' with img='capabilities/images/gas-pipeline-ai.webp' page_image='svgs/civil-projects-hexa.svg' page_image='svgs/oil-and-gas-news-hexa.svg' %}
{% endif %}

<div class="mobile-curved-bg">
  <div class="container">
    <div class="page-title">
      <img src="/static/svgs/mobile-page-title.svg" alt="page title" />
      <h4>{% trans "Oil And Gas News" %}</h4>
    </div>
    <h1>{% trans "Latest News" %}</h1>
    <br>
    <div class="news-wrapper">
      {% for i in news %}
      <a class='go-to-details' href="{% url 'news:news-detail' i.id %}">
      <div class="news-card">
        <div class="news-img">
          <div class='news-date'>
            {% if LANGUAGE_CODE == 'fa' %}
              <p>{{i.jalali_date|date:'Y/m/d'}}</p>
            {% else %}
              <p>{{i.created|date:'Y/m/d'}}</p>
            {% endif %}
          </div>
          <img src="{{i.image.url}}" alt="news image">
        </div>
        <h2 class="news-title">
          {{i.title}}
        </h2>
        <p class="news-summery">
          {{i.summery|safe}}
        </p>
      </div>
      {% endfor %}
    </div>
    </a>
  </div>
</div>
{% endblock content %}
{% comment %} {% block more_js %}
  <script>
    console.log("{{data.navid.0|escapejs}}");
  </script>
{% endblock more_js %} {% endcomment %}

news/templates/news.html
{% extends 'base.html' %} {% load i18n %} {% load static %} 
{% block translateFa %}{% url 'news:news-detail' news.id %}{% endblock translateFa %} 
{% block translateEn %}{% url 'news:news-detail' news.id %}{% endblock translateEn %} 
{% block translateEnMobile %}{% url 'news:news-detail' news.id %}{% endblock translateEnMobile %} 
{% block translateFaMobile %}{% url 'news:news-detail' news.id %}{% endblock translateFaMobile %}
{% block more_css %}
  <link rel="stylesheet" href="{% static 'news/css/news.css' %}">
  {% if LANGUAGE_CODE == 'fa' %}
    <link rel="stylesheet" href="{% static 'news/css/news-fa.css' %}">
  {% endif %}
{% endblock more_css %}
{% block title %}{% trans "Oil And Gas News" %}{% endblock title %}
{% block content %}
{% if LANGUAGE_CODE == 'fa' %}
  {% include 'inc/hero.html' with img='capabilities/images/gas-pipeline-ai.webp' page_image='svgs/civil-projects-hexa.svg' page_image='svgs/oil-and-gas-news-hexa-fa.svg' %}
{% else %}
  {% include 'inc/hero.html' with img='capabilities/images/gas-pipeline-ai.webp' page_image='svgs/civil-projects-hexa.svg' page_image='svgs/oil-and-gas-news-hexa.svg' %}
{% endif %}

<div class="mobile-curved-bg">
  <div class="container">
    <div class="page-title">
      <img src="/static/svgs/mobile-page-title.svg" alt="page title" />
      <h4>{% trans "Oil And Gas News" %}</h4>
    </div>
    <div class="title">
      <h2>{{news.title}}</h2>
      <div class="news-date">
        {% if LANGUAGE_CODE == 'fa' %}
          <p>{{news.jalali_date|date:'Y/m/d'}}</p>
        {% else %}
          <p>{{news.created|date:'Y/m/d'}}</p>
        {% endif %}
      </div>
    </div>
    <br>
    <div class="news-img">
      <img src="{{news.image.url}}" alt="news main image">
    </div>
    <br>
    <p>{{news.body|safe}}</p>
  </div>
</div>
{% endblock content %}